media:
  input: media
  output: media
content:
  - name: posts
    label: Blog Posts
    type: collection
    path: '_posts'
    view:
      fields: [title, description, category, tags, cover]
    fields:
      - name: title
        label: Judul
        type: string
      - name: description
        label: Deskripsi
        type: text
      - name: category
        label: Kategori
        type: string
      - name: tags
        label: Tag
        type: text
      - name: cover
        label: Gambar Cover
        type: image
      - name: body
        label: Isi Artikel
        type: rich-text
