media:
  input: assets/images
  output: public
content:
  - name: page
    label: Page
    type: collection
    path: "content"
    view:
      fields: [title, slug, description, draft, comment]
    fields:
      - name: title
        label: Judul Artikel
        type: string
      - name: slug
        label: Custom URL
        type: string
      - name: description
        label: Meta Deskripsi
        type: text
        options:
         minlength: 50
         maxlength: 160
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: comments
        label: Aktifkan Komentar
        type: boolean
        default: false
      - name: body
        label: Artikel
        type: rich-text
  - name: posts
    label: Blog Posts
    type: collection
    path: "content/posts"
    view:
      fields: [title, description, date, categories, tags, cover, draft, comment]
    fields:
      - name: title
        label: Judul
        type: string
      - name: slug
        label: Custom URL
        type: string
      - name: description
        label: Meta Deskripsi
        type: text
        options:
         minlength: 50
         maxlength: 160
      - name: date
        label: Date
        type: date
      - name: categories
        label: Kategori
        type: select
        multiple: true
        options:
          values:
            - value: ["Teknologi"]
              label: Teknologi
            - value: ["Coretan"]
              label: Coretan
            - value: ["Blogging"]
              label: Blogging
      - name: tags
        label: Tag
        type: string
      - name: cover
        label: Gambar Cover
        type: image
        option:
          media: 
            input: assets/images
      - name: draft
        label: Draft
        type: boolean
        default: true
      - name: comments
        label: Aktifkan Komentar
        type: boolean
        default: true
      - name: body
        label: Isi Artikel
        type: rich-text

