media:
  input: assets/images/
  output: public/
content:
  - name: posts
    label: Blog Posts
    type: collection
    path: 'content/posts/'
    view:
      fields: [title, description, category, tags, cover]
    fields:
      - name: title
        label: Judul
        type: string
      - name: description
        label: Deskripsi
        type: text
      - name: categories
        label: Kategori
        type: string
      - name: tags
        label: Tag
        type: text
      - name: cover
        label: Gambar Cover
        type: image
      - name: body
        label: Isi Artikel
        type: rich-text
