content:
  - name: posts
    label: Posts
    path: content/posts/
    type: collection
    fields:
     - name: title
       label: Judul Artikel
       type: string
     - name: text
       label: article
       fields:
         - name: content
           label: Isi artikel
           type: rich-text