media:
  input: assets/images/
  output: public/
content:
  - name: page
    label: Page
    type: collection
    path: 'content'
    view:
      fields: [title, slug, description, cover, draft, comment]
    fields:
      - name: title
        label: Judul
        type: string
      - name: slug
        label: Custom URL
        type: string
      - name: description
        label: Deskripsi
        type: text
      - name: draft
        label: draft
        type: boolean
        default: false
      - name: comment
        label: Aktifkan Komentar
        type: boolean
        default: true
      - name: body
        label: Isi Artikel
        type: rich-text
  - name: posts
    label: Blog Posts
    type: collection
    path: 'content/posts'
    view:
      fields: [title, description, date, categories, tags, cover, draft, comment]
    fields:
      - name: title
        label: Judul
        type: string
      - name: slug
        label: Custom URL
        type: string
      - name: description
        label: Deskripsi
        type: text
      - name: date
        label: Date
        type: date
      - name: categories
        label: Kategori
        type: select
        options:
          values: [ Teknologi, Coretan, Blogging ]
      - name: tags
        label: Tag
        type: string
      - name: cover
        label: Gambar Cover
        type: image
        option:
          media: 
            input: assets/images
      - name: draft
        label: draft
        type: boolean
        default: true
      - name: comment
        label: Aktifkan Komentar
        type: boolean
        default: true
      - name: body
        label: Isi Artikel
        type: rich-text

