content:
  - name: posts
    label: Posts
    path: content/posts/
    type: collection
    fields:
     - name: title
       label: Judul Artikel
       type: string
     - name: text
       label: article
       fields:
        - name: description
          label: Description
          type: rich-text