content:
  - name: posts
    label: Posts
    path: content/posts/
    type: collection
    fields:
     - name: title
       label: Judul Artikel
       type: string
     - name: content
       label: Text Content
       type: rich-text
      # ... fields defined here ...