media:
  input: assets/images/
  output: public/
content:
  - name: posts
    label: Blog Posts
    type: collection
    path: 'content/posts/'
    view:
      fields: [title, description, categories, tags, cover, draft]
    fields:
      - name: title
        label: Judul
        type: string
      - name: description
        label: Deskripsi
        type: text
      - name: categories
        label: Kategori
        type: string
      - name: tags
        label: Tag
        type: string
      - name: cover
        label: Gambar Cover
        type: image
        options:
          path: ./assets/images/
          extensions: [jpg, png, jpeg]
      - name: draft
        label: draft
        type: boolean
        default: true
      - name: body
        label: Isi Artikel
        type: rich-text
