backend:
  name: github
  repo: jundi14/myblog
media_folder: static/img
public_folder: /img
commit_messages:
  create: Create {{collection}} “{{slug}}”
  update: Update {{collection}} “{{slug}}”
  delete: Delete {{collection}} “{{slug}}”
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/posts'
    media_folder: '../../static/img/posts/{{slug}}'
    create: true
    nested:
      depth: 2
      summary: "{{title}}"
    extension: "md"
    format: "frontmatter"
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Judul Artikel', name: 'title', widget: 'string' }
      - { label: 'slug', name: 'slug', widget: 'string' }
      - { label: 'Tanggal Posting', name: 'date', widget: 'datetime' }
      - { 
          label: 'Meta Deskripsi', 
          name: 'description', 
          widget: 'string'  
        }
      - { 
          name: "comments", 
          label: "Aktifkan Komentar", 
          widget: "boolean"
        }
      - { label: 'Cover', name: 'cover', widget: 'image' } 
      - { label: 'Tulisan', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    folder: 'content'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Judul Halaman', name: 'title', widget: 'string' }
      - { label: 'Meta Deskripsi', name: 'description', widget: 'string' }
      - { label: 'Isi Artikel', name: 'body', widget: 'markdown' }
    
