backend:
  name: git-gateway
  branch: master 
media_folder: static
public_folder: public
collections:
  # Content type for pages
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    media_folder: "images"   # khusus folder ini
    public_folder: "/public/images"
    editor:
      preview: false
    fields:
      - { name: "title", label: "Judul", widget: "string" }
      - name: "cover"
        label: "Cover Image"
        widget: "image"
        media_folder: "images"   # path cover image
        public_folder: "/public/pages"
      - { name: "body", label: "Isi Halaman", widget: "markdown" }

# Content type for posts
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
     - { label: "Judul Artikel", name: "title", widget: "string" }
      - { label: "Custom URL", name: "slug", widget: "string" }      
      - { label: "Tanggal Posting", name: "date", widget: "datetime" }
      - { label: "Meta Deskripsi", name: "description", widget: "string" }
      - { Label: "Kategori Artikel", name: "categories", widget: "string" }
      - { label: "Hero Image", name: "cover", widget: "image" }
          media_folder: "assets/images/posts"   # biar hugo bisa pakai resources
          public_folder: "/public/images/posts"
      - { label: "Isi Artikel", name: "body", widget: "markdown" } 