backend:
  name: git-gateway
  branch: master 
media_folder: images
public_folder: public
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Judul Artikel', name: 'title', widget: 'string' }
      - { label: 'Tanggal Posting', name: 'date', widget: 'datetime' }
      - { label: 'Meta Deskripsi', name: 'description', widget: 'string' }
      - { Label: "Kategori Artikel", name: "categories", widget: "string" }
      - { label: 'Hero Image', name: 'cover', widget: 'image' }
      - { label: 'Isi Artikel', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'page'
    folder: 'content'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Judul Halaman', name: 'title', widget: 'string' }
      - { label: 'Tanggal Posting', name: 'date', widget: 'datetime' }
      - { label: 'Meta Deskripsi', name: 'description', widget: 'string' }
      - { label: 'Hero Image', name: 'cover', widget: 'image' }
      - { label: 'Isi Artikel', name: 'body', widget: 'markdown' }
    
