backend:
  name: github
  repo: jundi14/myblog
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
media_folder: img
public_folder: public
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Judul Artikel', name: 'title', widget: 'string' }
      - { label: 'Tanggal Posting', name: 'date', widget: 'datetime' }
      - { 
          label: 'Meta Deskripsi', 
          name: 'description', 
          widget: 'string',  
          pattern: ["^.{0,160}$", "Deskripsi maksimal 160 karakter"]  
        }
      - { 
          name: "comments", 
          label: "Aktifkan Komentar", 
          widget: "boolean", 
          default: true,       
          hint: "Centang untuk mengaktifkan komentar"
        }
      - { label: 'Hero Image', name: 'cover', widget: 'image' } 
      - { label: 'Isi Artikel', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    folder: 'content'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Judul Halaman', name: 'title', widget: 'string' }
      - { label: 'Meta Deskripsi', name: 'description', widget: 'string' }
      - { label: 'Isi Artikel', name: 'body', widget: 'markdown' }
    
